name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Build and deploy on server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER << 'EOF'
            cd ./client/jsClient
            git pull origin main
            yarn install
            yarn build
            sudo mv dist/* /var/www/duk
            sudo systemctl restart nginx
          EOF