name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Build and deploy on server
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER << 'EOF'
            # Build the project
            cd ./client/jsClient
            git pull origin main
            yarn install
            yarn build
          EOF

      - name: Move static and nginx files
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SERVER: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$SERVER << 'EOF'
            # Move built files to deployment director
            cd ./client/jsClient
            sudo rm -rf /var/www/duk/*
            sudo mv dist/* /var/www/duk/

            # Copy Nginx config
            sudo cp nginx/nginx.conf /etc/nginx/sites-available/duk

            # Set up Nginx
            sudo ln -sf /etc/nginx/sites-available/duk/ /etc/nginx/sites-enabled/
            sudo nginx -t
            sudo systemctl restart nginx
          EOF